import { Card, Grid, Typography } from "@mui/material";
import React from "react";
import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";

import styles from "./index.css";

import CardWithImage from "../component/CardwithImage";
import BoxSx from "../component/Box";
import MasonryImageList from "../component/ImageList";

const HomeWrapper = styled.div`
  ${styles}
`;

export default function Home() {
  const [users, setUsers] = React.useState([]);

  const f = async () => {
    const res = await fetch("https://reqres.in/api/users/");
    const json = await res.json();
    setUsers(json.data);
  };
  React.useEffect(() => {
    f();
  }, []);

  return (
    <HomeWrapper>
      <Head>
        <title>mui-design</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <Typography variant="h1" className="title">
          MUI design with nextjs
        </Typography>

        <Typography paragraph className="description">
          Grid and card
        </Typography>
        {/* <MasonryImageList /> */}

        <Grid
          container
          spacing={1}
          sx={{ flexWrap: "wrap", maxWidth: "800px" }}
        >
          {users.map((user) => (
            <Grid item sm={6} key={user.id}>
              <CardWithImage data={user} />
            </Grid>
          ))}
        </Grid>
      </main>
    </HomeWrapper>
  );
}
