import { Card, Grid, Typography } from "@mui/material";
import React from "react";
import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";

import MasonryImageList from "../../component/ImageList";

export default function ImageList() {
  return (
    <div>
      <Head>
        <title>mui-design</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <Typography variant="h1" className="title">
          MUI design with nextjs
        </Typography>

        <Typography paragraph className="description">
          Image List
        </Typography>
        <MasonryImageList />
      </main>
    </div>
  );
}
